version: '3.8'
services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - timescale_volume:/var/lib/postgresql/data
volumes:
  timescale_volume:
    external: true
