services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
    networks:
      - shared_network
    ports:
      - "5341:80"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  seq_data:
    external: true
networks:
  shared_network:
    external: true
