version: '3'

services:
  mongodb:
    container_name: mongodb_container
    image: mongo:5.0.8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db
volumes:
  mongodb_volume:
    external: true
