services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx-config/:/etc/nginx/conf.d/:ro
      - ./proxy_params:/etc/nginx/proxy_params:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - shared_network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - shared_network
networks:
  shared_network:
    external: true
