services:
  influxdb:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=organization
      - DOCKER_INFLUXDB_INIT_BUCKET=starter

volumes:
  influxdb2-data:
  influxdb2-config:

# https://docs.influxdata.com/influxdb/v2/install/?t=Docker

# To see the generated token:
# docker exec -it influxdb2 /bin/bash
# influx auth list
